# Generated by Django 4.1.7 on 2023-03-10 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("context", models.CharField(max_length=512)),
                ("created_at", models.DateField()),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="userid",
                        to="accounts.user",
                    ),
                ),
                (
                    "UserName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="username",
                        to="accounts.user",
                    ),
                ),
                (
                    "parent_post_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timeline.post",
                    ),
                ),
            ],
        ),
    ]
