# Generated by Django 4.1.7 on 2023-03-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="UserName", new_name="name",
        ),
    ]
