# Generated by Django 4.1.7 on 2023-03-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_password"),
        ("timeline", "0002_rename_username_post_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="post.accounts.name+",
                to="accounts.user",
            ),
        ),
    ]
