# Generated by Django 4.1.7 on 2023-03-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0008_alter_post_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="UserID",),
    ]
