# Generated by Django 4.1.7 on 2023-03-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0012_alter_post_userid_alter_post_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="name", field=models.CharField(max_length=20),
        ),
    ]
