# Generated by Django 4.1.7 on 2023-03-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0015_alter_post_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="id",),
        migrations.AlterField(
            model_name="post",
            name="parent_post_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
