# Generated by Django 4.1.7 on 2023-03-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="PhoneNumber",),
        migrations.RemoveField(model_name="user", name="password",),
    ]
