# Generated by Django 4.1.7 on 2023-03-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_phonenumber_remove_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
